CREATE TYPE USER_TYPE_ENUM AS ENUM ('user', 'admin');

CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	PHONE NUMERIC(20),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_TYPE USER_TYPE_ENUM DEFAULT 'user' NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL,
    IMAGE VARCHAR(255),
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE RESERVATION_TYPE_ENUM SET ENUM('Interno', 'Externo', 'Externo Coberto');

CREATE TABLE RESERVATIONS (
    RESERVATION_ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    PRODUCT_ID INT REFERENCES PRODUCTS(PRODUCT_ID),
	PEOPLE_QTD NUMERIC(20),
    RESERVATION_DATE VARCHAR(30) NOT NULL,
    RESERVATION_TIME VARCHAR(30) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	AREA RESERVATION_TYPE_ENUM NOT NULL ,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PURCHASE (
    PURCHASE_ID SERIAL PRIMARY KEY,    
	USER_ID INT REFERENCES USERS(USER_ID),
    PRODUCT_ID INT REFERENCES PRODUCTS(PRODUCT_ID),
	QUANTITY DECIMAL(10, 0) NOT NULL,
	TOTAL DECIMAL(10, 2) NOT NULL,
    DELIVERY_DATE VARCHAR(30),
    DELIVERY_TIME VARCHAR(30),
	STATUS VARCHAR(20) DEFAULT 'Pendente' NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);